### ISSUE TITLE
Instructions for newbs

### ISSUE THREAD

**Issue by That-Dude** [MoonRide303/Fooocus-MRE#1]
I'm sure this is NOT the best approach but this worked for me on Windows.

Assuming you already have the original Fooocus 7z file downloaded, installed and working.

Close Fooocus if its running.
cd into the parent folder that contains Foooccus / python-embeded / run.bat
`git clone https://github.com/MoonRide303/Fooocus.git Fooocus-MoonRide`

duplicate run.bat to run-moonride.bat

Copy (or move) your models folder from `Fooocus/models` to `Fooocus-MoonRide/models`

edit run-moonride.bat and change Fooocus to Fooocus-MoonRide

double click the run-moonride.bat

**Comment by MoonRide303** [comment]
@That-Dude To be honest I simply use `python .\launch.py` from Anaconda PowerShell launched in main Fooocus directory - worked fine for the original Fooocus repository, and works for this little fork of mine, too :).

**Comment by MoonRide303** [comment]
> > @That-Dude To be honest I simply use `python .\launch.py` from Anaconda PowerShell launched in main Fooocus directory - worked fine for the original Fooocus repository, and works for this little fork of mine, too :).
> 
> ...Googles Anaconda PowerShell :-)

If you already have working Python environment, then don't bother - [Anaconda](https://www.anaconda.com/download) is Python distribution popular among data scientists, but it has its own quirks (managing depencies using conda can be pain in the back, for example). What I really meant is that I simply use python to execute `launch.py`, and it works fine. I didn't even downloaded Fooocus archive, just the repo from the github - I already had SDXL model files, so I hardlinked them to proper Fooocus directories, and that was all :).

**Comment by barepixels** [comment]
Forgot to thank [That-Dude](https://github.com/That-Dude)  This instruction save me some hairs

**Comment by aimarxjg** [comment]
> @That-Dude To be honest I simply use `python .\launch.py` from Anaconda PowerShell launched in main Fooocus directory - worked fine for the original Fooocus repository, and works for this little fork of mine, too :).

Hello, my first contact with FOC saw your modified version, and I especially like it. I don't know how to start it (I saw the novice tutorial, but I don't understand the Anaconda PowerShell at all). I had to replace the downloaded compressed file with the original FOC file and it can also work. Now I have a few questions for you to answer, thank you
1 Does it affect the use of such replacement files? For example, some settings are missing? Do two versions have to coexist?
2 I will replace it and run it again. Is it automatically updated? Is it the original FOC or your modified version?
3 Is the version of the replacement file unavailable after the update? For example, change back to the original FOC?

**Comment by MoonRide303** [comment]
@aimarxjg I've prepared standalone package for Fooocus-MRE, you can download it from here : [Fooocus-MRE-v1.0.40.7z](https://github.com/MoonRide303/Fooocus-MRE/releases/download/v1.0.40/Fooocus-MRE-v1.0.40.7z). Please let me know, if it works for you.

**Comment by aimarxjg** [comment]
> @aimarxjg I've prepared standalone package for Fooocus-MRE, you can download it from here : [Fooocus-MRE-v1.0.40.7z](https://github.com/MoonRide303/Fooocus-MRE/releases/download/v1.0.40/Fooocus-MRE-v1.0.40.7z). Please let me know, if it works for you.

Thank you for informing me. Thank you. Thank you. Thank you~

**Comment by MoonRide303** [comment]
Should be easy enough to use even for people who never touched git, Python and pip - you can just download the archive, and run the .bat. Closing.
