### ISSUE TITLE
Feature request: Generate Forever

### ISSUE THREAD

**Issue by barepixels** [MoonRide303/Fooocus-MRE#10]
I post this request at lllyasviel/Fooocus but I will post this here too.  Pretty sure lllyasviel have higher-piority things to do

In A1111 you can right-click the generate button and select "generate forever" then right-click again when you want to stop.

This way you can have Fooocus working all night while you sleep or all day while you are at work.

This addition doesn't affect the simple and elegant interface.

**Comment by xM0DI** [comment]
+1 will helpful if it is added

**Comment by MoonRide303** [comment]
Done (ported SD web UI implementation, commit [57319f4](https://github.com/MoonRide303/Fooocus-MRE/commit/57319f43fd00a5e347657ad4bbb3fe6e1440baa7)).
