### ISSUE TITLE
BUG: user_path_config.txt (solved)

### ISSUE THREAD

**Issue by barepixels** [MoonRide303/Fooocus-MRE#111]
On Windows, every time MRE Launch user_path_config.txt gets replaced.  Model starts download

**Comment by metallicatw** [comment]
me too @@

**Comment by MoonRide303** [comment]
Fixed in v2.0.78.1.

**Comment by metallicatw** [comment]
Hi~I found the solution. Just modify the user_path_config.txt and delete the original paths.json!

**Comment by MoonRide303** [comment]
Still problem with relative paths, sigh...

**Comment by mirek190** [comment]
my config txt looks like that 


{
    "modelfile_path": "E:\\DIFFUSION\\Fooocus-MRE\\models\\checkpoints",
    "lorafile_path": "E:\\DIFFUSION\\Fooocus-MRE\\models\\loras",
    "embeddings_path": "E:\\DIFFUSION\\Fooocus-MRE\\models\\embeddings",
    "clip_vision_path": "E:\\DIFFUSION\\Fooocus-MRE\\models\\clip_vision",
    "controlnet_path": "E:\\DIFFUSION\\Fooocus-MRE\\models\\controlnet",
    "styles_path": "E:\\DIFFUSION\\Fooocus-MRE\\sdxl_styles",
    "wildcards_path": "E:\\DIFFUSION\\Fooocus-MRE\\wildcards",
    "vae_approx_path": "E:\\DIFFUSION\\Fooocus-MRE\\models\\vae_approx",
    "upscale_models_path": "E:\\DIFFUSION\\Fooocus-MRE\\models\\upscale_models",
    "inpaint_models_path": "E:\\DIFFUSION\\Fooocus-MRE\\models\\inpaint",
    "fooocus_expansion_path": "E:\\DIFFUSION\\Fooocus-MRE\\models\\prompt_expansion\\fooocus_expansion",
    "temp_outputs_path": "E:\\DIFFUSION\\Fooocus-MRE\\outputs"
}


If I mood it to 

{
    "modelfile_path": "../models/checkpoints/",
    "lorafile_path": "../models/loras/",
    "embeddings_path": "../models/embeddings/",
    "clip_vision_path": "../models/clip_vision/",
    "controlnet_path": "../models/controlnet/",
    "vae_approx_path": "../models/vae_approx/",
    "fooocus_expansion_path": "../models/prompt_expansion/fooocus_expansion/",
    "upscale_models_path": "../models/upscale_models/",
    "inpaint_models_path": "../models/inpaint/",
    "styles_path": "../sdxl_styles/",
    "wildcards_path": "../wildcards/",
    "temp_outputs_path": "../outputs/"
}

still is override to old one .... 

Fooocus-MRE is creating folder for models on top of  Fooocus-MRE tree ...

**Comment by MoonRide303** [comment]
I corrected just corrected last commit - it should work fine, now. If it fails to update please download last zip realease (the small one, without env - v2.0.19 will do), and try again.

**Comment by mirek190** [comment]
> I just corrected last commit - it should work fine, now. If it fails to update please download last zip realease (the small one, without env - v2.0.19 will do), and try again.

That helped.
Thank you.
