### ISSUE TITLE
BUG: Image Style(s) broken (solved)

### ISSUE THREAD

**Issue by barepixels** [MoonRide303/Fooocus-MRE#112]
Not loading styles from "sdxl_styles" folder

**Comment by MoonRide303** [comment]
@barepixels Please try replacing content of Fooocus-MRE folder with files with last release package (v2.0.19 - the small one, without env) and starting again with with update - should be working now.

**Comment by barepixels** [comment]
Since this is a big update, I have decided to do a fresh install.  So far I renamed the existing Fooocus folder to Fooocus-MRE-OLD and am now downloading the installer.  Will report back

**Comment by barepixels** [comment]
UPDATE  from fresh Fooocus version: 2.0.19 to Fooocus version: 2.0.78.1 and seem to be working now.  Need to test
