### ISSUE TITLE
Please add hires to generate high resolution imge directly

### ISSUE THREAD

**Issue by wodsoe** [MoonRide303/Fooocus-MRE#115]
Please add hires to generate high resolution imge directly

**Comment by barepixels** [comment]
1) someone can't do hires because of a weak video card.
2) sometimes I would do a batch of a few hundred and would not want to do auto-hires on all of them

**Comment by barepixels** [comment]
then you got my vote

**Comment by Acephalia** [comment]
There are multiple ways to upscale now which is the same as hiresfix.
