### ISSUE TITLE
[Enhancement Request] Implementation of FreeU

### ISSUE THREAD

**Issue by Acephalia** [MoonRide303/Fooocus-MRE#118]
@MoonRide303 I know you want to keep things simple as much as possible but this might be an invaluable addition given the potential enhancement at no cost. Happy for you to decide how to best integrate it but also open to discuss ideas on how to add it to the UI as well. 

Official Source : https://github.com/ChenyangSi/FreeU
Comfy Implementation: https://github.com/comfyanonymous/ComfyUI/commit/fd93c759e278f832b149bc5b0150a8b437c48c77
Extension for A1111 : https://github.com/ljleb/sd-webui-freeu

cheers!

**Comment by MoonRide303** [comment]
@Acephalia I tried it on latest ComfyUI, and seems to be working fine (just b1, b1, s1, s2 need to be closer to 1.0 for SDXL) - it should be doable in Fooocus, too.

**Comment by MoonRide303** [comment]
@Acephalia Support for FreeU added in MRE v2.0.78.2 (commit [1ebf6a4](https://github.com/MoonRide303/Fooocus-MRE/commit/1ebf6a4742d4ac6351ee7d7dafe6fb213cc9624b)).

**Comment by Acephalia** [comment]
@MoonRide303 you are just on the ball aren’t you. Didn’t even have time to turn around and read the comments, you’ve already implemented it. 

Yes I was wondering what the effect would be I  was only able to read the paper and haven’t had a chance to try it out at all yet. I was hoping to get your thoughts on it as well.
From your comparison it does indeed feel like it’s affecting the higher frequencies more than anything else, albeit mildly. 

I have a feeling that the impact would be a bit more on 1.5 than XL. But I’ll need to give that hunch a test.

Thank you as always!

**Comment by MoonRide303** [comment]
@Acephalia I picked smaller values of parameters as defaults. If you want to have bigger impact you can try something like this:

FreeU enabled (b1 1.1, b2 1.2, s1 0.9, s2 0.2):
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/ef78a1b6-d6c8-4900-a139-f1cdf2f76216)

But it's not necesarilly better (it looks overcooked to me, with those values). This is something that migh need adjusting to particular prompt and/or what kind of output you desire (more or less defined, with higher or lower contrasts, etc.).

**Comment by Acephalia** [comment]
I finally ran some [tests ](https://imgur.com/a/mBNriW5) my self its really per case and experimental as you've indicated. I can't say for sure if it is always better either. Definitely fun to experiment with and I'm going to give the paper another read to see if I can figure out some method to the madness. 

<blockquote class="imgur-embed-pub" lang="en" data-id="a/mBNriW5"  ><a href="//imgur.com/a/mBNriW5">Fooocus-MRE - FreeU Comparisons </a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

I couldn't push the values higher than 2.0 though. Think the gradio slider is limited to 2.0.

**Comment by MoonRide303** [comment]
@Acephalia Restart MRE - I pushed the updated increasing allowed range to 3.0 about half an hour ago (FreeU author recommened ranges below 2.0, but I've found values beyond that able to produce useful results, too).

**Comment by Acephalia** [comment]
That would explain it. I’ve had it running for longer than that. 

Higher/lower values work fine on art style images. Falls apart on realistic stuff after a certain point both ways.

**Comment by MoonRide303** [comment]
I am still experimenting with different values to "feel it". Some combinations are quite nice:

FreeU enabled (b1 1.01, b2 1.02, s1 0.85, s2 0.15):
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/75d3daf8-5e06-40f6-a03f-a02722eb0776)

**Comment by Acephalia** [comment]
Oooh that does have some nice outputs. I've gone around in circles and settled at 1, 1, 1, 1 for some reason lol. It seems to have the best balance for  enhancing details. Almost like a hiresfix imho. 

Backbone Scaling Factor 2: As far as I can tell controls the coherency. Too low and the image breaks down. Too high and it becomes like a stencil and looses most details.

**Comment by MoonRide303** [comment]
@Acephalia The exact values you've given didn't work too well for my case, but I played a bit with the idea of reversed b1 / b2, s1 / s2, and got pretty nice results with this set:

FreeU enabled (b1 1.1, b2 1.01, s1 0.0, s2 0.9):
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/a467a493-a00b-4131-893e-f92888b53659)

**Comment by Acephalia** [comment]
Yep I made an edit shortly after it doesn't do well for anything other than art. 

B1: 1
B2: 1
S1: 1
S2: 1.2

Seems to be consistent in fixing little errors across the board, at least on my end 

> FreeU enabled (b1 1.1, b2 1.01, s1 0.0, s2 0.9):
Its so interesting, this completely changed my (art style) images. I don't hate the output in anyway but it was such a stark difference.

**Comment by Acephalia** [comment]
Hey hey are you questioning my fringe science approach? I joke. In my defence I have run about 50 prompts but you are right that's hardly anything. I was hoping "seems" indicated that no one should be taking my word haha. I suspect it's really going to come down to a use case scenario though. (Sticking with my conclusions for S2 at 1.2 though.)

But I have re-read the paper now and in conjunction with the 500 odd images I've generated tonight I think I understand what's going on. Will do a full write up with my findings and some sample images soon. 

I'm out for the night. This has been most fun, Au revoir!
