### ISSUE TITLE
Bug in FreeU?

### ISSUE THREAD

**Issue by gmthedoc** [MoonRide303/Fooocus-MRE#119]
It appears that the FreeU parameter once enabled remains active even though it appears to be disabled from the interface.

How to play:
1) I load a prompt without FreeU and render.
2) I enable FreeU and render.
3) I disable FreeU and render again.
I would expect the images in step 1 and 3 to be the same instead step 2 and 3 generate the same image.

Is this a problem that only occurs to me?

**Comment by MoonRide303** [comment]
@gmthedoc Works fine for me:
1. Generate prompt.
2. Enable FreeU, generate.
3. Disable FreeU, generate.

I get the same output between 1 and 3. Any errors in the log?

**Comment by almfahd41** [comment]
> It appears that the FreeU parameter once enabled remains active even though it appears to be disabled from the interface.
> 
> How to play:
> 
>     1. I load a prompt without FreeU and render.
> 
>     2. I enable FreeU and render.
> 
>     3. I disable FreeU and render again.
>        I would expect the images in step 1 and 3 to be the same instead step 2 and 3 generate the same image.
> 
> 
> Is this a problem that only occurs to me?

try this valuse 

![Screenshot (6)](https://github.com/MoonRide303/Fooocus-MRE/assets/111824871/dcec6e2a-1bd9-4e6c-a026-50973b265062)

**Comment by MoonRide303** [comment]
@almfahd41 Still works for me. Are you sure you unchecked FreeU in step 3, or just loaded some old prompt? Cause loading prompt from older version (not having some parameters defined) will usually leave previously unknown settings (like FreeU) unchanged.

**Comment by almfahd41** [comment]
> @almfahd41 Still works for me. Are you sure you unchecked FreeU in step 3, or just loaded some old prompt? Cause loading prompt from older version (not having some parameters defined) might leave previously unknown settings (like FreeU) unchanged.

90 % sure that no porblem in my side , also i hope you make these values as the default values

**Comment by MoonRide303** [comment]
@almfahd41 If you want to have FreeU enabled by default and with those values, then you can do it via settings.json, like this:
```
    "freeu": true,
    "freeu_b1": 1.1,
    "freeu_b2": 1.2,
    "freeu_s1": 0.6,
    "freeu_s2": 0.4
```
See settings-example.json for complete list of all available settings.

**Comment by gmthedoc** [comment]
The problem recurred again, I did a clean installation from scratch and now it no longer seems to occur. Thank you all.

**Comment by MoonRide303** [comment]
RE-OPEN: I am not sure yet what exact reproduction steps are, but today after playing a bit with different models I was affected by this issue, using current MRE version (v2.0.78.3). Needs investigation and fixing.
