### ISSUE TITLE
A black and white image as input, always output a black and white image

### ISSUE THREAD

**Issue by skywolf123** [MoonRide303/Fooocus-MRE#122]
A black and white image as input, using the prompt words "a bunch of flowers in a glass vase", regardless of the adjustment of Start Step and Denoise, will output a black and white image, even if I add the prompt words "color photograph"
![背景 拷贝](https://github.com/MoonRide303/Fooocus-MRE/assets/34243902/4eaad4c9-b7ff-4d5f-9e4b-c90faa82e5fc)

**Comment by MoonRide303** [comment]
@skywolf123 Seems to be working fine for me (tested in MRE v2.0.78.2):

input:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/4e2ac5e7-d5ab-4801-a589-48ed59495e25)

output:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/a1e9a885-32c1-4266-a78e-ab2173243ebe)

**Comment by skywolf123** [comment]
@MoonRide303 Thank you for your reply.
I did not try such an extreme parameter (start step 0, denoise 1), which does produce a color image.
I have tried parameters like (start step 0.1, denoise 0.9) and (start step 0.06, denoise 0.94) that still produce a black and white image.
It seems that the color of the input Image has a very large effect on the image-2-image function.
What I'm confused about is that the example is also a black and white image but with the default parameters or less extreme parameters you can produce a color image

![image](https://github.com/MoonRide303/Fooocus-MRE/assets/34243902/d57e30f2-b170-4395-b613-bcbeac4819b5)

**Comment by MoonRide303** [comment]
@skywolf123 Yes, the model managed to add a bit of colors in this case, but in general img2img is heavilly influenced by pixel colors from the input - but that's the whole idea of it, to be influenced by pixels from input image :). If you go with higher denoise (up to the max: start step 0, denoise 1) you'll increase chance of something different than input to be generated, but there is no single fixed denoising level that will always guarantee you to generate colors. For some combinations of prompt and seed model can generate BW image even in txt2img mode (even when not mentioning directly colors or bw), when not being influenced by any input image.

PS I am closing this issue, as there's nothing to be fixed here - it's just how diffusion models work.
