### ISSUE TITLE
BUG: Upscale (Fast 2x)

### ISSUE THREAD

**Issue by barepixels** [MoonRide303/Fooocus-MRE#124]
After MRE upscale, save the file, write to log... it locks up.  

CMD windows doesn't report Total time
No sound play
The "Stop" button won't go back to "Generate"

Tested, quit, and relaunched, repeat process, MRE still locked up

**Comment by MoonRide303** [comment]
Fixed (commit [4c2de2e](https://github.com/MoonRide303/Fooocus-MRE/commit/4c2de2ea5f11bc9ca54faf63315eb741427ceb77)).
