### ISSUE TITLE
Load last prompt is not working

### ISSUE THREAD

**Issue by barepixels** [MoonRide303/Fooocus-MRE#127]
Load last prompt is not working for me.  
After generating few images with different prompts, I hit reload browser then load last prompt button... nothing happens
After generating few images with different prompts, quit then relaunch then load last prompt button... nothing happens
I can't seem to find "last_prompt.json" file in Fooocus-MRE folder  (path.py)

**Comment by MoonRide303** [comment]
@barepixels It should be created in (and loaded from) outputs folder - works for me, so far. Are you doing anything extra with outputs? If there is any scenario where it doesn't work need to know how to reproduce this problem, first.

**Comment by barepixels** [comment]
It's not there.  No I have done anything with output folder.  Infact I have not moved/redirect it anywhere (path.json or user_path_config.txt)

**Comment by MoonRide303** [comment]
@barepixels Ok, I think I see the problem - it needs to have enabled saving metadata as json. I always had it enabled, and that's why it worked for me. It should be pretty simple fix.

**Comment by barepixels** [comment]
I choose not to have saving metadata as json.  Don't want to deal with extra files

**Comment by MoonRide303** [comment]
Fixed (commit [67c78b3](https://github.com/MoonRide303/Fooocus-MRE/commit/67c78b3e00a3fd048ab112e50875d54ecab0a6dd)).

**Comment by barepixels** [comment]
It's working now. Thank you
