### ISSUE TITLE
 HELP~WHAT IS Style Iterator ??

### ISSUE THREAD

**Issue by aimarxjg** [MoonRide303/Fooocus-MRE#138]
Hello, what is the function of Style Iterator? (Sorry, I'm not very familiar with COMFYUI) It seems that the slider numbers are not adjustable. For every additional art style I add from the SDXL STYLE menu above, will the numbers below decrease by 1? What is this used for? XYZ? (According to the usage tutorial, selecting multiple art styles will generate an image that combines multiple artistic effects, rather than comparing different styles.) Does this feature need to be adjusted in conjunction with the number of art styles selected above to adjust the number of generated images? Can you explain the specific usage method？ Thank you~

**Comment by barepixels** [comment]
It will generate an image for each style.  Read more here  https://github.com/MoonRide303/Fooocus-MRE/discussions/133

**Comment by aimarxjg** [comment]
> 它将为每种风格生成一个图像。请在此阅读 [ #133](https://github.com/MoonRide303/Fooocus-MRE/discussions/133)

thx
