### ISSUE TITLE
The UI interface is stuck

### ISSUE THREAD

**Issue by Crazy-CYZ** [MoonRide303/Fooocus-MRE#14]
The image has been generated, but the UI interface is stuck.

![_20230820222722](https://github.com/MoonRide303/Fooocus-MRE/assets/89187812/c99f9c7c-86cc-49b8-92b8-65b42a8b314a)

**Comment by barepixels** [comment]
what version are you using?  there are report 
Cannot generate image after 1.0.39 update 
https://github.com/lllyasviel/Fooocus/issues/221

**Comment by Crazy-CYZ** [comment]
@barepixels This issue seems to only appear on fooocus-MRE, I also had this problem in 1.0.36 before, and now I update 1.0.39 still appears, this is a random event. I use a 3060 12G graphics card, restart fooocus can be used normally, but the problem still happens randomly.

**Comment by barepixels** [comment]
My bad, I meant to say am using 1.0.39 MRE just fine

**Comment by MoonRide303** [comment]
@Crazy-CYZ I could look into it, but I'd need some reproduction steps, first (or at least in what type of scenario it happens most often) - I didn't experience this problem, so far.

It's probably something related to handling gradio queue (I've found an issue with similar error messages here: [gradio #4061](https://github.com/gradio-app/gradio/issues/4061)), but I don't know what exactly is causing it in case of Fooocus.

**Comment by Crazy-CYZ** [comment]
@MoonRide303 
![微信截图_20230822160909](https://github.com/MoonRide303/Fooocus-MRE/assets/89187812/6debb707-22be-4c85-a8e8-0bf99c9ff2dc)

![微信截图_20230822160936](https://github.com/MoonRide303/Fooocus-MRE/assets/89187812/934eaf17-f259-4ccf-883e-d5c73c72d100)

![微信截图_20230822161028](https://github.com/MoonRide303/Fooocus-MRE/assets/89187812/15a679ef-26ce-4ed5-a3e1-c7e88f765c07)

**Comment by MoonRide303** [comment]
@Crazy-CYZ Could you try updating aiohttp (`pip install aiohttp==3.8.5`) and see if it helps?

**Comment by Crazy-CYZ** [comment]
@MoonRide303 It seems to be solved. After updating, I used it for a few days, and the problem did not appear again!

**Comment by MoonRide303** [comment]
@Crazy-CYZ Nice to hear - closing the issue, then.
