### ISSUE TITLE
[Bug] Image Style(s)

### ISSUE THREAD

**Issue by barepixels** [MoonRide303/Fooocus-MRE#141]
I have only 1 json file in the sdxl_styles folder:  styles_favorite.json.  Inside of that I have an entry at top of my list

```
	{
		"name": "None",
		"prompt": "{prompt}",
		"negative_prompt": ""
	},
```
In settings.json I set the default style to be

`    "style": "None",`

Fooocus-MRE does not respect the default setting in settings.json

Everytime I launch or reload I get  "Default (Slightly Cinematic)"

**Comment by MoonRide303** [comment]
@barepixels It seems you're using old settings-example.json as a base. Using current version as a base, and then change in settings.json:
```    "styles": ["Default (Slightly Cinematic)"],```
->
```    "styles": [],```

or just adjust this single entry - you should get what you want, then (no style selected on launch).
