### ISSUE TITLE
[BUG] Style Iterator

### ISSUE THREAD

**Issue by barepixels** [MoonRide303/Fooocus-MRE#148]
1)
With no style in settings.json `"styles": [],` set
and my **favorite_styles.json** DOES  NOT contain **Default (Slightly Cinematic)**
When using Style Iterator, a **Default (Slightly Cinematic)** gets generated anyway

It's a very minor bug.  I have been throwing it away after it was created

2)
Style Iterator ON/OFF is not in settings.json, well this is not a true bug, just missing, an inconsistency

@MoonRide303 Like I said, this is very minor, but I thought you might want to be aware

**Comment by MoonRide303** [comment]
@barepixels Style Iterator iterates over all styles you can select in the UI - so it's not really a bug, as Default style is always available (it's not read from json file, but included in the sources).
