### ISSUE TITLE
~help~ How to highlight options?

### ISSUE THREAD

**Issue by aimarxjg** [MoonRide303/Fooocus-MRE#15]
Hello, thank you for everything you have done, so that we can get the picture soon. Can you tell me the specific parameters of various options of the sampler used in the original FOC? If I want to display its options as highlights (such as orange). Used to refer to the comparison and then gradually reduce the parameters to adjust the appropriate time, because how to do it? (The original FOC picture quality is very good is very slow, the keywords are not very strict, and I am not familiar with XL new sampler, the picture is easy to feel plastic) Thank you ~

**Comment by MoonRide303** [comment]
@aimarxjg Default settings of Fooocus MRE (like steps, sampler, scheduler, etc.) and generated image should be exactly the same as those you get from original Fooocus (of the same version). I wanted my version to stay in sync in terms of output, but also allow users to customize the generation parameters when they need it.
