### ISSUE TITLE
img2img works

### ISSUE THREAD

**Issue by barepixels** [MoonRide303/Fooocus-MRE#16]
Just starting to play with img2img and am so happy.  Thank you

So far I only played with 2 sliders from the Advanced tab "Img2img Start Step" and "Img2img Denoise"

Also I want to as if you should make a "discussions" area on GitHub similar to what lllyasviel did here https://github.com/lllyasviel/Fooocus/discussions

I feel the "Issues" area should reserve for bug report.

**Comment by barepixels** [comment]
Let's call the image I upload "base image"
If I set random seed and batch 5 images
Does each of the batch images generate from the original "base image" or does 
batch image #2 get generated from batch image #1 THEN 
batch image #3 get generated from batch image #2
and so on

**Comment by MoonRide303** [comment]
@barepixels Good points, discussions enabled.

As for your question - both modes you described make sense (single image, and cycling over different images when more of them is available), but currently all images generated with img2img are using first image from the gallery as an input (so you can see different variants of it, generated using different seeds).

**Comment by MoonRide303** [comment]
@barepixels I've just implemented cyclic over input images as the default behaviour for img2img (available on moonride-main). So for example if you have image A, and image B as inputs, and batch size 4, then you will get 2 variants of image A, and 2 variants of image B.

And if you would like to have 4 variants of image A, then you simply load only image A as the source image.

**Comment by barepixels** [comment]
Loading more than one images (A & B) works

Not sure if I will ever load more than 1 because I want to focus on 1 task at a time.

What I would like to see is to have the original uploaded image "A" in the gallery.  This will serve 2 purpose

a) easy to compare before and after
b) Ensure all images generated with img2img are using the first image from the gallery (the uploaded image "A") as input

**Comment by MoonRide303** [comment]
@barepixels That could complicate UI, and I'd like to keep initial view as simple as possible - I will need to think a bit about how those function could be added to the UI, without making it cluttered.

**Comment by barepixels** [comment]
Maybe I have not said it clearly. Let me try to illustrate it with Photoshop.  Hang on

**Comment by barepixels** [comment]
This is what I am asking for
After generating 1 using img2img, to include the original (left image) with the generated version (right).  If more than 1 generated.  The original (left image) is always be at the top of the list

This will serve 2 purpose

a) easy to compare before and after
b) Ensure all images generated with img2img are using the first image from the gallery (the uploaded image on the left) as input

![Fooocus 1 0 40 MRE](https://github.com/MoonRide303/Fooocus-MRE/assets/92839033/17c1adae-5f23-4e5e-9351-1a1a0d34fdf6)

This does not affect the existing elegant interface.  No extra button or tab

**Comment by MoonRide303** [comment]
@barepixels Okay, that makes sense - I will try to figure out something like this.

**Comment by MoonRide303** [comment]
@barepixels I have initial idea for for the layout (and initial buggy implementation - it's currently messed up when preview is displayed, etc.) - I'd like to use two tabs for separate inputs and outputs galleries, it would look like that:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/b972b9a2-52cf-42d8-81fb-28f1683fbf54)
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/ecd2ba8d-26c3-4d88-bd48-506ca9d74dfb)

**Comment by barepixels** [comment]
that would work.  plus the preview will be bigger :-)

**Comment by MoonRide303** [comment]
@barepixels Implemented, available on moonride-main :).

**Comment by barepixels** [comment]
checking

**Comment by MoonRide303** [comment]
@barepixels Selection doesn't matter. If you have 1 image loaded as input, then it will use it for every generated output. If you will load 2, then it will cycle over these 2. So with imported images A and B, and batch size 8 you would get 4 variants of A, and 4 variants of B. If you loaded just A - you would get 8 variants of A.

You can also put inputs of completely different resolutions and aspect ratios - it will automatically upscale (or downscale) input image to roughly 1 megapixel each. And if you didn't set any input, but generated already something to Output - it will automatically import that for further processing :).

**Comment by barepixels** [comment]
Here is a potential problem I might have (I think)

1) I upload an image for img2img
2) I set a style I want
3) I set 32 to generate
4) It will give me 32 versions to compare
5) NOW if I press output to input
6) It will send ALL 32 to "input tab" (that is a lot, maybe too much, especially if 30 of them I do not like) I will have to wait for a long time OR quit CMD since there is no abort button

As for Denoise (in Advanced tab), default minimum is at 0.5?  What if I want 0.2

**Comment by MoonRide303** [comment]
@barepixels For now in situations like that simplest solution would be simply using "Load Image(s)", and picking those you want from the output folder.

I guess it would be nice to be able to send selected to the input gallery, but I am not sure how to proceed about that - I will need to take a deeper look into Gradio and Gallery in there, to see if and how it could be done.

Theoretically you could use very low denoise like that, but it wouldn't change input much - but if you find it useful / needed, then sure - I'll change it.

**Comment by barepixels** [comment]
Thank you for changing default Denoise.

The "simplest solution would be simply using "Load Image(s)", and picking those you want from the output folder." this is good enough.

I think you should stop/drop working on the "Output to Input" and focus on other modifications... such as Abort button.  haha

Also, I tried to just reload the browser hoping to abort the queue but it didn't work ... because there was no signal to tell Fooocus to stop. Duh on me.

**Comment by MoonRide303** [comment]
Next thing worth doing would be probably preparing easy to use (like download + click on .bat) package for the less experienced users. But both this and aborting the processing (also worth implementing - I agree on that) are separate issues / discussions, so let's stop it here. I consider img2img in current state as good enough for typical use cases, so I am closing this one :).
