### ISSUE TITLE
Support for Custom Styles

### ISSUE THREAD

**Issue by Marscog** [MoonRide303/Fooocus-MRE#20]
I have my own custom styles that I edit into the sdxl_styles.py file. But everytime I start Fooocus it updates everything and I lose my custom styles. Is there a way to keep my styles, and/or stop Fooocus from updating every start.

**Comment by MoonRide303** [comment]
@Marscog I will try figuring something out for this problem. In the meantime you can create `run-mre-no-update.bat` with that content:
```
cd Fooocus-MRE
..\Fooocus-MRE-env\python.exe -s launch.py
pause
```
and use it when you don't wan't to update.

**Comment by barepixels** [comment]
Fooocus - Diva Styles Expansion (70 additional styles) https://civitai.com/models/134005/fooocus-diva-styles-expansion

I tested it by
1) rename sdxl_styles.py to sdxl_stylesOLD.py
2) copy paste the NEW "sdxl_styles.py" to modules folder
3) launch Fooocus-MRE using "run-mre-no-update.bat"

Can't wait for "sdxl_styles.json"  The list of styles is getting too long

**Comment by MoonRide303** [comment]
@barepixels They are already merged in 1.0.41 (both vanilla, and MRE) :).

**Comment by barepixels** [comment]
lol

**Comment by MoonRide303** [comment]
@Marscog @barepixels Support for loading styles from JSON files added in MRE v1.0.45.1 (commit [0e9f13c](https://github.com/MoonRide303/Fooocus-MRE/commit/0e9f13c42ca9c04c5833431a9c1191ab445f4c40)) - just put them in sdxl_styles folder, and restart the app.

I also added tiny set of my own styles (mre-*) as a bonus :).
