### ISSUE TITLE
Feature Request: Control-LoRA and Revision

### ISSUE THREAD

**Issue by wodsoe** [MoonRide303/Fooocus-MRE#21]
Feature Request: Control-LoRA and Revision

https://huggingface.co/stabilityai/control-lora

**Comment by MoonRide303** [comment]
Looks doable - it's already supported by Comfy version used in MRE, so it's mostly about implementing those new workflows.

**Comment by MoonRide303** [comment]
@wodsoe Revision ready:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/cbeb3b2c-b978-4206-9d2c-5bfeb7a2e639)
->
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/06279532-0ab8-4c4c-ae5d-887f248def9b)

**Comment by MoonRide303** [comment]
@wodsoe Support for Control-LoRA: Canny Edge added in commit [36f3614](https://github.com/MoonRide303/Fooocus-MRE/commit/36f3614e19075f71e70f7791c345a29d6f7ff4ad) (available on moonride-main). Can be used in both txt2img and img2img modes.

Sample input and output:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/543cb013-a5da-40d9-845f-7b0028ce3a33)
->
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/7ed1a22d-ca73-409f-872e-bbd68ef92a12)
