### ISSUE TITLE
Keyboard shortcut to start generation

### ISSUE THREAD

**Issue by xM0DI** [MoonRide303/Fooocus-MRE#22]
Can we have or already have a keyboard shortcut to start generating?
same as we have in A1111 (ctrl+enter)

**Comment by MoonRide303** [comment]
Done (ported SD web UI implementation, commit [57319f4](https://github.com/MoonRide303/Fooocus-MRE/commit/57319f43fd00a5e347657ad4bbb3fe6e1440baa7)).
