### ISSUE TITLE
 Fooocus installer (Fooocus-MRE-v1.0.40.7z) zip is corrupt

### ISSUE THREAD

**Issue by barepixels** [MoonRide303/Fooocus-MRE#24]
I went to download Fooocus installer (Fooocus-MRE-v1.0.40.7z)  and the file is corrupt.  Both WinRar and 7zip show errors..  Then I downloaded again.  Same problem
![7-Zip](https://github.com/MoonRide303/Fooocus-MRE/assets/92839033/c0aa3b39-5d55-4a2b-a286-c5ffab245d63)

**Comment by MoonRide303** [comment]
@barepixels Please update to current 7-Zip version (at least 23.00). Current versions of 7-Zip use special filtering for ARM64 binaries, and 7-Zip older than 23.00 will struggle with unpacking them.

But taking into most people don't upgrade their software too often I will probably have to downgrade 7-Zip to older version and re-upload the release file.

**Comment by MoonRide303** [comment]
I've re-upladed release files - current ones should be extractable without errors also on older 7-Zip versions. Closing.
