### ISSUE TITLE
subfolders

### ISSUE THREAD

**Issue by randykoala** [MoonRide303/Fooocus-MRE#26]
have set custom paths in the paths.py but it doesnt recognise subfolders for checkpoints or loras

**Comment by passionlu** [comment]
Please edit the “paths-example.json ”file to set a custom path and save the file as“ paths.jsion” file @randykoala

**Comment by MoonRide303** [comment]
Support for loading files from subfolders added in v2.0.14 (ported from [RuinedFooocus](https://github.com/runew0lf/RuinedFooocus)) - closing.

**Comment by Targren** [comment]
> Support for loading files from subfolders added in v2.0.14 (ported from [RuinedFooocus](https://github.com/runew0lf/RuinedFooocus)) - closing.


2.0.78.5 -  It supports loading them, but doesn't seem to detect them in subfolders on startup, so tries to download them again
