### ISSUE TITLE
Ability to save as JPG

### ISSUE THREAD

**Issue by Aamir3d** [MoonRide303/Fooocus-MRE#28]
Could you add the ability to save as JPG? (With EXIF info that contains metadata)
A1111 has this functionality.
I'm trying out MRE today, and it is great as a simple image generator.

I can't also find the DPM++ 2M scheduler in the dropdown.

**Comment by MoonRide303** [comment]
@Aamir3d dpmpp_2m added:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/cc087420-1c58-462a-97af-1bfb539651db)

I am adding support for JPEGs to the wishlist.

**Comment by Aamir3d** [comment]
Thank you very much - the program is very intuitive and the advanced options are great for advanced users without bogging down the interface!

**Comment by MoonRide303** [comment]
@Aamir3d Support for JPEGs added - please check if it works for your.

**Comment by Aamir3d** [comment]
> @Aamir3d Support for JPEGs added - please check if it works for your.

Just confirmed it's working. I'm going to check if it's saving the JPG exif info/metadata.
Thank you for processing this so fast.

**Comment by MoonRide303** [comment]
@Aamir3d Yup, I implemented it with metadata support - tested it a bit more today (and found + fixed one bug in prompt loading area - but it affected all the formats, wasn't specific to JPEGs), seems to be working fine. Closing :).
