### ISSUE TITLE
Great Job! but would it support SD 1.5 models?

### ISSUE THREAD

**Issue by xy185** [MoonRide303/Fooocus-MRE#29]
Hi MoonRide303,

This version is sooooooo cooooooool!

I like it so much for new feathers like the prompt information in png, and image 2 image

Well, after I modified the path-example.json and wishing to use sd 1.5 models and loras in fooocus-mre, it seems do not work well.
Like this :example, I changed the model to reacatoonanimeV4.safetensors, and same seed, same prompt( which is fairy girl) and same negative prompt, result is like this:
![2023-08-28_19-55-24_8667](https://github.com/MoonRide303/Fooocus-MRE/assets/13744916/42a9275a-edfe-4b41-b42f-203e44178705)

and the same setting on webui, the result is like this:
![00200-2065610250-Fairy girl](https://github.com/MoonRide303/Fooocus-MRE/assets/13744916/79b51a69-67f5-46b5-9d96-1fa83649e4ad)

I'm not sure what's the problem, would you like to fix this issue?

Thank you so much : )
👍

**Comment by MoonRide303** [comment]
@xy185 Fooocus was designed as UI exclusively for SDXL, so I think it just refused to load non-SDXL model you've selected, and image was probably generated using last SDXL model you've picked. You can check the log file (log.html in output folder) to see what model was used to generate particular image.

**Comment by MoonRide303** [comment]
Theoretically it could be possible to support SD (comfy backend used by Fooocus supports SD models), but it would complicate the UI - older SD models works best using 512x512 (1.5) or 768x768 (2.1) as base resolutions, for example. So... while I still enjoy and sometime use older SD models, for now I'd rather focus on main purpose of Fooocus, that is being solid UI for the SDXL.

And as for anime fairies in Fooocus - you can try sai-anime style, and SDXL variants trained on anime, like [CounterfeitXL](https://civitai.com/models/118406/counterfeitxl) :).
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/eb9a37da-a5b8-46ea-835a-3bedbbe9a7b1)

**Comment by Aamir3d** [comment]
One of the reasons to have a 1.5 model support is the speed of generation and resource consumption. SDXL doesn't play very well with systems that have 4/6GB VRAM and 16GB RAM.

For example, I can generate an image at 768 x something in A1111 in less than 10 seconds using only 4 GB of VRAM in a laptop GPU.
For SDXL, the same generation (1024+ res) in my laptop GPU takes over 2 minutes because of memory requirements with Fooocus-MRE (tried this just now).

It's a different matter on my desktop, where I've got a 12GB GPU and 32 GB RAM, SDXL is much better in that scenario.

**Comment by MoonRide303** [comment]
@Aamir3d Yeah, that's true - SDXL isn't really usable on GPUs below 8 GB RAM.

**Comment by xy185** [comment]
> Theoretically it could be possible to support SD (comfy backend used by Fooocus supports SD models), but it would complicate the UI - older SD models works best using 512x512 (1.5) or 768x768 (2.1) as base resolutions, for example. So... while I still enjoy and sometime use older SD models, for now I'd rather focus on main purpose of Fooocus, that is being solid UI for the SDXL.
> 
> And as for anime fairies in Fooocus - you can try sai-anime style, and SDXL variants trained on anime, like [CounterfeitXL](https://civitai.com/models/118406/counterfeitxl) :). ![image](https://user-images.githubusercontent.com/130458190/263806811-eb9a37da-a5b8-46ea-835a-3bedbbe9a7b1.png)

@MoonRide303 Thanks so much for your reply!
 I was not so familiar with XL, thanks for your kindly guide, and I would try the style and new model,

Finallly, thanks for your great work: Fooocus-MRE, it's perfect!

**Comment by MoonRide303** [comment]
Limited support for SD models added in v2.0.78.3 (commit [6d47547](https://github.com/MoonRide303/Fooocus-MRE/commit/6d475475d1eb821abefaa2a42f479eb47eee86d7)).

Test image generated using [DreamShaper 8](https://civitai.com/models/4384/dreamshaper):
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/f5d0d92d-2499-4b9b-8912-ba24a6213586)


Not supported functions: refiner, Control-LoRAs, Revision, inpainting, outpainting. You need to manually pick compatible resolution and LoRAs, too.

**Comment by Aamir3d** [comment]
Thank you @MoonRide303 ! So, image2image will still work, but not inpaint?

**Comment by MoonRide303** [comment]
@Aamir3d Yup. Inpainting in Fooocus is based on supplementary model designed for SDXL (custom type of LoRA) - there is no easy way to make it work with non-SDXL models.
