### ISSUE TITLE
Adding a toggle button to the resolutions

### ISSUE THREAD

**Issue by Aamir3d** [MoonRide303/Fooocus-MRE#30]
There are a bunch of resolutions / image sizes , but as we can see now, the dropdown is TOO long.
I propose having either a toggle button for landscape/ portrait mode or an aspect ratio button to quickly switch without getting bogged down in the long dropdown.

![image](https://github.com/MoonRide303/Fooocus-MRE/assets/122131887/42e370d5-b110-44ad-b6cc-1424a4e5cb5a)

![image](https://github.com/MoonRide303/Fooocus-MRE/assets/122131887/5b80b9d0-2036-4547-8a6b-a66cff6be63a)

Addendum.
I don't see any 16:9 / 9:16 ratios or 16:10, which are pretty common and widely used. For example 
I feel those are necessary additions and should have been part of the original project too.

I've calculated some resolutions that might be useful
1152 x 720 - 16:10
1152 x 648 - 16:9
1280x720 - 16:9

Edit 2:
(Note from the GUI perspective - the dropdown is indeed way too long now, and serves as a distraction rather than a 'quick' generation.
For other members contributing to the project, it might be helpful to discuss / see if it might be more feasible to say enter a width or height value, and use the toggle to fill in the other resolution based on aspect, or just enter values in both fields (faster).

**Comment by barepixels** [comment]
1152 x 720 - 16:10
1152 x 648 - 16:9
1280x720 - 16:9
do not use.  720 and 648 does not divided by 64 evenly

Use 1344 x 768 for 16:9

**Comment by Aamir3d** [comment]
> 1152 x 720 - 16:10 1152 x 648 - 16:9 1280x720 - 16:9 do not use. 720 and 648 does not divided by 64 evenly
> 
> Use 1344 x 768 for 16:9

Interesting, thank you for the info.

**Comment by MoonRide303** [comment]
@Aamir3d The resolution list is limited on purpose - I wanted it to be in sync with officially supported resolutions list used for SDXL training (as defined in [SDXL paper](https://arxiv.org/abs/2307.01952), Appendix I). And as Gradio (UI framework used by Fooocus) doesn't support that kind of toggles / filters for dropdown lists, I am leaving resolution list as it is - closing.

**Comment by Aamir3d** [comment]
No problem. 
Just asking - is there a possibility to include a resolution box instead - this is because just scrolling through the list trying to find a resolution/aspect you need is a waste of time (which defeats the purpose of having a simple clean UI).
Maybe do a Resolution X  Resolution Y box, and display resolutions below in the dropdown.

**Comment by barepixels** [comment]
There are a lot of resolutions on that list that nobody would ever use.
