### ISSUE TITLE
Feature Request: Image Browser/Photo Album

### ISSUE THREAD

**Issue by valdecircarvalho** [MoonRide303/Fooocus-MRE#31]
Hello! First of all, thanks a million for putting this together! 
I would love to see something like a Image Browser / Photo Album feature like the one available on InvokeAI.
For those running it on a headless server on Linux, it's a bit difficult to find the files after a while.
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/1709654/e87361bb-72df-4bc8-b346-1365f67719b7)

**Comment by Aamir3d** [comment]
This would add to the complexity of the project (the idea being a simple interface, compared to the multiple tabs/workflows that A1111 or ComfyUI have). 
(I personally have no issues with an image browser either way)

Would something like https://github.com/zanllp/sd-webui-infinite-image-browsing work? This also has a standalone mode.

**Comment by valdecircarvalho** [comment]
Looks perfect! Thanks a lot!
