### ISSUE TITLE
change `settings-example.json` to `settings.json`

### ISSUE THREAD

**Issue by MohamedAliRashad** [MoonRide303/Fooocus-MRE#33]
I think it will be easier for everyone if `settings-example.json` became `settings.json` and people edit in it directly to change the defaults without renaming it and go through the documentations.

**Comment by barepixels** [comment]
It's really not a big deal.  Copy, rename, edit.  Plus you have the "settings-example.json" as backup incase you get syntax errors

**Comment by MoonRide303** [comment]
@MohamedAliRashad It's on purpose - if I had settings.json in the repository, and you customized it, then git (used for pulling updates from github) would detect conflicts, and process would get more complicated - I wanted to avoid that.

In future I might just add button to save current settings, or restore the default values - that would probably be best solution from user perspective.

**Comment by barepixels** [comment]
Which led me to make this post
https://github.com/MoonRide303/Fooocus-MRE/discussions/35

**Comment by MohamedAliRashad** [comment]
@MoonRide303 I understand your point from a development prospective.
I will close this issue now.
