### ISSUE TITLE
Request to bring a custom resolution box

### ISSUE THREAD

**Issue by Aamir3d** [MoonRide303/Fooocus-MRE#38]
@MoonRide303 I know you closed the toggle issue, but not a big deal.
I'm trying to work with F-MRE, but that long dropdown of resolutions is way too long. I showed this to a GUI/UX person who felt the same way, in what is otherwise a very very usable and clean interface.

A 'nice to have' : A custom resolution box be implemented for X / Y (Width, Height) resolution, and this will allow people to simply type in their required resolution and start working rather than scroll through the list each time they want a different res.

**Comment by Ptbird1** [comment]
2nd this, I'm lucky enough to have a beefy PC and like making 1920x1200 images, mostly for paintings and landscapes but SDXL can handle the beefier resolutions, maybe hide it in advanced so people don't start complaining about how their 512x4000 image looks bad

**Comment by barepixels** [comment]
forgot the link to the original paper but for SDXL one should use these dimensions (all numbers are divided by 65 evenly)
![aspect ratio](https://github.com/MoonRide303/Fooocus-MRE/assets/92839033/a3616bbb-cc9f-40a5-9fc6-5f19de7003af)

For now, I have a reference sheet that I must open and look at when I want to change resolutions

896x1152 for 3:4 or 4:5 crop
1152x896 for 4:3 or 5:4 crop

832 x1216 for 2:3 crop
1216x832 for 3:2 crop

1344x768 for 16:9 crop

they are the ideal size to generate with minimal crop loss to match common industry ratios.  Yes you will have to crop some off before you go to print

**Comment by Ptbird1** [comment]
That reference sheet is super helpful! Definitely gonna be saving that :)

**Comment by barepixels** [comment]
In an ideal world, we would be able to make our own list for the pull-down and save as a josn file.  This will shorten the list:
1) not having to see resolutions we would never use
2) change the wording in the pull-down, such as "1408 x 704 spherical 360 pano"
2) no scrolling madness
3) short and elegant
4) even add (not recommended) odd sizes

**Comment by barepixels** [comment]
check this out
![SDXL Aspect Ratio](https://github.com/MoonRide303/Fooocus-MRE/assets/92839033/cbc33efc-7926-4509-9a2d-a4c694d1daf4)

**Comment by MoonRide303** [comment]
@barepixels
1. Those aspect ratio values are not correct (I use math to calculate correct AR for given resolution in MRE).
2. I'd rather stick to official SDXL resolution list by default.
3. I will look into customising resolution list (via resolutions.json, or something like that), so people who would like to use fewer resolutions could adjust that list to their needs in simple way.

**Comment by barepixels** [comment]
possible solutuon?

@MoonRide303 please provide 2 versions: original "resolutions.py" and "alternative-resolutions.py"

The "alternative-resolutions.py" displays the pull-down menu that read like this. This way we can opt for the shorter version by changing the file name when Fooocus gets an update

![SDXL Aspect Ratio](https://github.com/MoonRide303/Fooocus-MRE/assets/92839033/af09d728-3e96-44e9-90f9-c42d3d7a281d)

**Comment by MoonRide303** [comment]
Done. I've added support for custom resolutions lists (you can define your own in resolutions.json), and also for custom resolutions (you can just type something like "1280x640" in Resolution field, now). Commit [d2942a0](https://github.com/MoonRide303/Fooocus-MRE/commit/d2942a03952496342be571d45c10c42221dd4f3b).
