### ISSUE TITLE
[Request] - Multi Gpu usage and manual

### ISSUE THREAD

**Issue by Spirit-Catt** [MoonRide303/Fooocus-MRE#41]
The software works fine with 1 gpu, but it completely ignores other. It would be nice if it could automaticly generate few images at the same time depending on the amount of gpus computer has. Also it's now hard to understand how to use ImgToImg mode properly for a new user, so I think it's worth adding some information about how to use that program in ReadMe or somewhere else. Thanks for your work!

**Comment by MoonRide303** [comment]
@Spirit-Catt I'd rather leave lower-level operations like this on the Comfy backend side - you can see and subscribe to [Comfy issue #162](https://github.com/comfyanonymous/ComfyUI/issues/162).

As for using Image-2-Image I tried make it as simple as possible - you just need to load Input image, enable Image-2-Image, and press generate. If you want output image to be more like input, then just lower the denoise (in Image-2-Image settings).

**Comment by Spirit-Catt** [comment]
> @Spirit-Catt I'd rather leave lower-level operations like this on the Comfy backend side - you can see and subscribe to [Comfy issue #162](https://github.com/comfyanonymous/ComfyUI/issues/162).
> 
> As for using Image-2-Image I tried make it as simple as possible - you just need to load Input image, enable Image-2-Image, and press generate. If you want output image to be more like input, then just lower the denoise (in Image-2-Image settings).

Well, I think it would be still valuable to know about MRE features like revision properly. It could be done not only in readme but also as tooltips. That wouldn't have a great effect on ui appearance, but would help a lot of people=)

**Comment by MoonRide303** [comment]
@Spirit-Catt I guess you're right. Featuers that are obvious to me might not be so obvious for people who never used ControlNets, for that example. I agree that some kind of documentation / manual / wiki with examples how those more advanced features work would help - adding to the wishlist.

Tooltips woudn't hurt, either (though they're not natively supported by Gradio (SFAIK), so I'd probably need add some custom code out of UI framework - which I am trying to avoid).

**Comment by Spirit-Catt** [comment]
Thanks!
