### ISSUE TITLE
Crosspost: Fooocus is much slower than official replicate sdxl model. Any way to speed up？

### ISSUE THREAD

**Issue by lanyusan** [MoonRide303/Fooocus-MRE#42]
https://github.com/lllyasviel/Fooocus/issues/264

It looks Fooocus maintainers are busy with other things. 

I am wondering if you guys have any ideas? 

Thanks

**Comment by MoonRide303** [comment]
@lanyusan I replied in original issue - please double-check your testing methodology. In my environment Fooocus-MRE runs as fast as reference UI using same backend (ComfyUI) - both doing about 4.5 it/s when using same generation parameters. I don't see much space for improvement here, so - closing.
