### ISSUE TITLE
Please, add to output time taken to render image. In the log also, if possible

### ISSUE THREAD

**Issue by ptits** [MoonRide303/Fooocus-MRE#44]
start_time = time.time()
imgs = pipeline.process(p_txt, n_txt, steps, switch, width, height, seed, sampler_name, scheduler,
            cfg, base_clip_skip, refiner_clip_skip, input_image_path, start_step, denoise, callback=callback)
        end_time = time.time()
elapsed_time = end_time - start_time
print(f"\033[91mTime taken: {elapsed_time} seconds\033[0m")
![shot_230823_214522](https://github.com/MoonRide303/Fooocus-MRE/assets/13587736/b01187d8-6cbd-4e00-8b7b-bb4d39127c3c)

**Comment by MoonRide303** [comment]
Done ([6c50f79](https://github.com/MoonRide303/Fooocus-MRE/commit/6c50f79ced502c6abd5185f9c39a41ad089352b6)).
