### ISSUE TITLE
any way to see log.html with gradio?

### ISSUE THREAD

**Issue by ptits** [MoonRide303/Fooocus-MRE#45]
I had focus installed on server with --share
How can I see log.html file with gradio link?

Can we have someting like this - https://[4afc4f0bf5bbcf259.gradio.live/internal/log.html

**Comment by MoonRide303** [comment]
@ptits Done (commit [526309a](https://github.com/MoonRide303/Fooocus-MRE/commit/526309a84d29caf597acca662740932df2053f9d)) - I've added links in Misc tab.
