### ISSUE TITLE
photo editing

### ISSUE THREAD

**Issue by amir-eshaqy** [MoonRide303/Fooocus-MRE#5]
Hi, first of all I have to say that your work is excellent.Is it possible to upload a photo (or send a link) and edit based on the uploaded photo, if there is such a feature, please guide me to use it.

**Comment by MoonRide303** [comment]
It's not available in vanilla Fooocus (2 open issues for having img2img there), and it might be a bigger change, so I'd rather wait for [lllyasviel](https://github.com/lllyasviel) to comment on any of them.

**Comment by MoonRide303** [comment]
@amir-eshaqy I've just implemented img2img, available on moonride-main :).

**Comment by MoonRide303** [comment]
Implemented, closing.

@amir-eshaqy to use it just mark "Image-2-Image" before generation. You also need to have at least one image in the gallery, that could be used as an input (can be either previously generated image, or anything else loaded from file using "Load Image(s)" button). If you need your generated image to look more (or less) like the source, then you can adjust Image-2-Image settings in Advanced tab.
