### ISSUE TITLE
[ Request ] Possibility to save custom styles

### ISSUE THREAD

**Issue by Jisevind** [MoonRide303/Fooocus-MRE#58]
It would be great if we could save our own custom styles, the positive and negative prompts. 
Maybe have it in its own dropdown.

**Comment by MoonRide303** [comment]
@Jisevind I don't plan adding saving custom styles, cause I want to keep UI as simple as possible, and add only absolutely necessary buttons. But I added support for loading custom styles from JSON files in v1.0.45.1 - you can look at original styles in sdxl_styles folder, and make your own styles in in similar fashion (JSON files from this folder will be loaded on start).

**Comment by barepixels** [comment]
MoonRide303 just added this feature:

In "sdxl_styles" folder there are 4 included styles.json.

You can edit but NOT add new styles.json NOR rename the json files because these 4 are hardcoded in modules/sdxl_styles.py 

Just make a backup then add to or remove the styles in either 4 files

**Comment by Jisevind** [comment]
@barepixels It seems to load all json files in the styles folder, I was able to create a new json file and add new styles and it shows up in the list.

**Comment by MoonRide303** [comment]
@barepixels You CAN add more files there. Those 4 listed in sdxl_styles.py are just to have those default styles loaded and listed as first.

**Comment by barepixels** [comment]
OK  very cool.  Happy dance

**Comment by barepixels** [comment]
But what if I don't want them to be first.  I think I want my custom one first.

**Comment by MoonRide303** [comment]
@barepixels You can rename those files to something like styles_1.json styles_2.json etc. - they will be loaded in alphabetical order of file names, then.

**Comment by barepixels** [comment]
Answer to my own questions:

I made my own style.json  "sdxl_styles_1.json"  It has just one custom entry
I move the default 4 json files into a sub diretory as backup

Relaunch Fooocus, it did it's update and did not tries to download the missing default 4 json files   YAY
and Fooocus style menu only shows 1 entry.  YAY

Happy Dance

**Comment by barepixels** [comment]
Actualy the current menu gives me 3 choice

1) None with a check mark,  I set it to None in settings.jon
2) cinematic-default
3) Favorites Style

Where did #2 "cinematic-default" come from?

**Comment by MoonRide303** [comment]
@barepixels cinematic-default is the default built-in style of Fooocus - I wanted to keep this one in the code. All the other that came from external sources (sai / twri / diva and mre) are in JSON files.

**Comment by barepixels** [comment]
OK  thanks.  BTW am loving generate forever
