### ISSUE TITLE
img2img dosent follow selected resolution

### ISSUE THREAD

**Issue by LakesideDreamer** [MoonRide303/Fooocus-MRE#62]
The supported official resolutions are very low resolution, so to get high resolution output without bad composition I tried to give 1920x1080px in resolutions to do img2img from low resolution to high.
But this doesn't work and there is no high res fix option as well so all the output images with such low resolution are not usefull at all unless i do img2img in A1111 with output of foocus.
That just wastes time and i would rather just use A1111 at that point.
There should be some way to to do from low res to high in Fooocus.

**Comment by barepixels** [comment]
You just need to be patient.  Fooocus is a very young software and MoonRide303 is the only programmer for this fork.  Am sure there are a lot of features MoonRide303 wants but it will take time.  If the current Fooocus is a waste of your time then don't use it... or ask for a refund.  lolol

**Comment by LakesideDreamer** [comment]
> 

I said using foocus and then A1111 for higher resolution is waste of time not just using foocus. Foocus is great at what it does but just pointing out that the output images can really be useful with higher resolution.

**Comment by barepixels** [comment]
Try this

ComfyUI : Ultimate Upscaler - Upscale any image from Stable Diffusion, MidJourney, or photo!

https://youtu.be/CxB47DMEyYQ?si=_okZHeyvKogwzGjb

**Comment by LakesideDreamer** [comment]
> 

If i wanted to use comfy then i would have created a workflow with all the styles plus at the end high resolution lol 
I don't like spaghetti and A1111 isn't that optimized so i am using foocus to save time. So you get the idea what i meant in my original comment. 
To be clear i am not being ungrateful i am just pointing out what important thing is missing for it to be standalone solution for SDXL webui

**Comment by ikmalsaid** [comment]
Foocus is targeted at simplifying the best of SDXL. Remember that. In the meantime, you can plan your workflows.

**Comment by LakesideDreamer** [comment]
L
