### ISSUE TITLE
log.html and gradio. lifehuck and suggestion

### ISSUE THREAD

**Issue by ptits** [MoonRide303/Fooocus-MRE#63]
I use FocusMRE and it is great. 
I use it locally (much faster then Automatic1111 on my RTX 2080 8GB) and also on linux server with gradio and --share.

May be I am stupid but I found no way to see log.html when using gradio.

Lifehuck: I see that Automatic1111 can open links like:
https://47c763360a19fc9500.gradio.live/file=/data/ptits/a1111/stable-diffusion-webui/outputs/txt2img-images/2023-09-07/

So, I set output path for FocusMRE то stable-diffusion-webui/outputs/txt2img-images/ and then I can open
https://47c763360a19fc9500.gradio.live/file=/data/ptits/a1111/stable-diffusion-webui/outputs/txt2img-images/2023-09-07/log.html with no problem

But I need to have Automatic working on sever.

I found no directory than gradio of FocusMRE can access, is there one? (like in Automatic). (searching for gr.Interface had now results)

Can you make default "outputs" directory be accessible from gradio?
Something like:
https://47c763360a19fc9500.gradio.live/file=/data/ptits/FocusMRE/outputs/2023-09-07/log.html

**Comment by MoonRide303** [comment]
@ptits You can access current and previous log file from the UI using links in Misc tab - I've added it about 3 days ago, in MRE v1.0.45.1. It looks like that:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/502e3bd1-9228-47fd-bf69-286b7a8a0426)

It works in Colab and in shared mode, too.

Please let me know if it suits your needs.

**Comment by MoonRide303** [comment]
I've moved those links (along with the one to Fooocus Advanced documentation) to the Settings tab, so they're easier to access. Seems to be working properly for me, so - closing.
