### ISSUE TITLE
Save default setting for use next time

### ISSUE THREAD

**Issue by Aamir3d** [MoonRide303/Fooocus-MRE#65]
A good to have would be 
An option to save settings like the resolution, style, batch and output as a default. 
(for example, I need to select JPG with metadata and change the resolution every time), so that the next launch of the application, the same settings do not have to be applied again.

**Comment by barepixels** [comment]
1) Duplicate "settings-example.json"
2) Change the new file name to "setting.json"
3) Edit "setting.json"

**Comment by Aamir3d** [comment]
Thank you @barepixels - appreciate the quick help.
