### ISSUE TITLE
[Bug] Stop button stop working

### ISSUE THREAD

**Issue by barepixels** [MoonRide303/Fooocus-MRE#70]
Stop button stop working in single and batch mode

Generate Forever and Cancle Generate Forever still working

**Comment by MoonRide303** [comment]
@barepixels Yeah, I just noticed it today - it was "improvement" caused by newer Comfy version (commit [326577d](https://github.com/comfyanonymous/ComfyUI/commit/326577d04c99590cbf91324f507fdc2c7d37832d)). I reverted Comfy version to just before that change - it works fine, now.
