### ISSUE TITLE
Feature request: Wildcards / dynamic prompts

### ISSUE THREAD

**Issue by joelewing** [MoonRide303/Fooocus-MRE#71]
Support for wildcards or dynamic prompts would be great!

[https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards](https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards)

**Comment by barepixels** [comment]
Here is a case for wildcards.

Finding a pretty face by going through a list of female names.

**Comment by barepixels** [comment]
@MoonRide303  I just realized https://github.com/runew0lf/RuinedFooocus has wildcards

Wildcards are now supported place see wildcards\colors.txt for an example. In your prompt make sure you type __<filename>__ to activate ie shiny new __colors__ Chevrolet pickup truck with big wheels

**Comment by MoonRide303** [comment]
Support for wildcards added in v2.0.19 (commit [1a775ed](https://github.com/MoonRide303/Fooocus-MRE/commit/1a775ed49b16db86a8e5ee9abf481c128ac98fd7)). `__color__` (based on [CSS2 color keywords](https://www.w3.org/TR/CSS22/syndata.html#color-units)) is included as the default wildcard example.

It's based on [RuinedFooocus](https://github.com/runew0lf/RuinedFooocus) (hi there @runew0lf ;]), just adjusted to FooocusV2. I also decided for this feature to be seed-stable - so for the same seed MRE will generate exactly same image when loading your past prompts using wildcards.
