### ISSUE TITLE
Getting worse results than official Fooocus

### ISSUE THREAD

**Issue by sodayo9** [MoonRide303/Fooocus-MRE#75]
Hi thanks for the great repo to add img2img to Fooocus. I am a video maker and I am making a video to describe the history of fruits (like watermelons) in Ancient Mesopotamia as an educational material for an online history course, and I am using Fooocus-MRE to generate images with “the woman in desert eating a watermelon”.

However, I am getting much worse results in MRE, making it almost impossible for me to continue the work (though MRE has img2img). I noticed that almost in all cases, the MRE gives worse results than official Fooocus. I studied how random seed works, an then I am able to uncheck the “random” in seeds:

In official Fooocus
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/125098761/08e0a1ef-7b37-4f35-a10d-cc9d2cf1273f)

In MRE
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/125098761/78096e21-a0dc-43ed-9fc2-b50193341f19)

The result from official Fooocus
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/125098761/bb70871e-074f-4ed5-ae7e-ef5aeece88b8)
(the results are super good and the second image is EXACTLY what I want - though it does not have img2img!)

The result from Fooocus-MRE
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/125098761/e3f9c9b0-5b73-4055-a3b0-bf1c4ecd96b5)
(the left one has unwanted heavy makeup that is not in the prompts and a slight distortion of the face; the right one is even worse, what the heck is in the background???)
(And all skins are more plastic-look than official Fooocus)

so I studied a bit more and find that even with simple prompts like the "dragon" in the official guide, the official Fooocus is still much better - there must be something wrong in MRE

Official Fooocus
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/125098761/f252c47d-524c-42bd-9950-2847a6e2c994)
(the styles are super good and the results are diverse enough for me to further work on it to improve prompts)

Fooocus-MRE
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/125098761/bccf8d07-002a-4f47-957b-e6ada6310f55)
(the eyes on the left dragon is twisted; and the atmosphere is not as good as official one)
(the official Fooocus seems to have way more consistent and harmonious color compositions in most cases)

Again, really thanks for bring this MRE! But the current results make it very difficult for me to continue my works; we should really ask official Fooocus to support img2img.

**Comment by MoonRide303** [comment]
@sodayo9 It should be pixel-perfect 1:1 in v2.0.0 release.

Last 3 weeks latest Comfy had issue with float autocasting in CLIP that might be causing slight differences like that. I was investigating it 2 days ago, and talked a bit with comfy about it. It started with commit [f081017](https://github.com/comfyanonymous/ComfyUI/commit/f081017c1a20a5d9cfae9005fd0898502e3356be), and comfy fixed it yesterday in commit [fb3b728](https://github.com/comfyanonymous/ComfyUI/commit/fb3b7282034a37dbed377055f843c9a9302fdd8c). I updated Comfy version in MRE few hours after fix was available, and MRE 2.0.0 has this fix included already.

Comparison below, vanilla and MRE v2.0.0:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/6a3fb391-28df-48d4-b84c-43def232d5d4)
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/d8ef467f-5a7d-415e-a15b-732a5590ed64)

**Comment by sodayo9** [comment]
Thanks for the fix!
