### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by ikmalsaid** [MoonRide303/Fooocus-MRE#76]
Good day, I'm having an issue while starting up Fooocus-MRE V2 for the first time.

Here is the last output from the command prompt:
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>

It occurs during the below process:
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_expansion.bin" to E:\Personal\Downloads\FooocusMRE\Fooocus-MRE\models\prompt_expansion\fooocus_expansion\pytorch_model.bin

Thank you and I hope to have it fixed so that I can use it again.

Best regards!

**Comment by MoonRide303** [comment]
@ikmalsaid Works for me, in both browser and from the code - after removing this model:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/714c998e-4e6b-4cf8-8cfd-cd26da0e4d6d)

Are you using full v2.0.0 release, with its own standalone environment?

You can also try opening https://huggingface.co/lllyasviel/misc/tree/main in the browser, and see if you have any warnings related to the certificated there. You can click on the lock icon, then certificate / details, and see the details - it should look more or less like that:
![image](https://github.com/MoonRide303/Fooocus-MRE/assets/130458190/251932be-c92f-4c35-82f6-724831b7e348)

**Comment by ikmalsaid** [comment]
Thanks for the response @MoonRide303 !

I'm able to manually download the file instead and it worked well.

Closing the issue.
