### ISSUE TITLE
Fooocus-MRE doesn't support subfolders within paths..

### ISSUE THREAD

**Issue by RuFse2** [MoonRide303/Fooocus-MRE#78]
In Automatic1111, I have subfolders within both Checkpoints and Loras to be able to nicely organize hundreds of files.

In Fooocus-MRE it seems I can only use one path and any sub paths won't be read by Fooocus-MRE.

IS this something you could support?

EX:

"path_checkpoints": ["F:/SDFILES/Models/","F:/SDFILES/Models/SDXL/", etc..],

**Comment by MoonRide303** [comment]
Yes, it should be doable - ComfyUI has similar feature.

But in this use case you've described (you having separate folders for SDXL base models and SDXL LoRAs) simplest way would be just setting proper folders (directly to those SDXL models) via `paths.json` - as Fooocus supports only SDXL models. Something like that should work (just adjust the paths):
```
{
    "path_checkpoints": "F:/models/checkpoints/SDXL/",
    "path_loras": "F:/models/loras/SDXL/",
}
```

**Comment by aimarxjg** [comment]
> Yes, it should be doable - ComfyUI has similar feature.
> 
> But in this use case you've described (you having separate folders for SDXL base models and SDXL LoRAs) simplest way would be just setting proper folders (directly to those SDXL models) via `paths.json` - as Fooocus supports only SDXL models. Something like that should work (just adjust the paths):
> 
> ```
> {
>     "path_checkpoints": "F:/models/checkpoints/SDXL/",
>     "path_loras": "F:/models/loras/SDXL/",
> }
> ```

Thank  for your answer. This is very helpful. How should the other sampling methods be downloaded and added to MER?, Especially (UIPC and restart) they render images very quickly.

**Comment by MoonRide303** [comment]
@aimarxjg Available sampling methods and schedulers are limited by 3 factors:
1. They need to be exist in [ComfyUI](https://github.com/comfyanonymous/ComfyUI) (which in turn uses code from [k-diffusion](https://github.com/crowsonkb/k-diffusion)).
2. They need to be compatible with changes to sampling made by Lvmin in vanilla Fooocus (not all are).
3. They need to result in reasonable quality output (no artifacts) when changed as single parameter (all the other settinsg left at default values). I did some tests some time ago (around v1.0.45) and observed for example that "normal" scheduler doesn't work well with the default sampler ("dpm_pp_2m_sde_gpu"), so I didn't add it to the list.

**Comment by MoonRide303** [comment]
Support for loading files from subfolders added in v2.0.14 (ported from [RuinedFooocus](https://github.com/runew0lf/RuinedFooocus)) - closing.

**Comment by technerd-official** [comment]
Is there an example on how to use subfolders? Can't get it to work it I just enter the main directory, the subfolders were not read.
