### ISSUE TITLE
Some LoRAs causing high VRAM usage

### ISSUE THREAD

**Issue by MoonRide303** [MoonRide303/Fooocus-MRE#80]
Default LoRA from SAI (`sd_xl_offset_example-lora_1.0.safetensors`) works fine (VRAM usage stay under 8 GB with it). But with some other LoRAs (even tiny ones, like [Bloodstained XL](https://civitai.com/models/118889/bloodstained-xl) VRAM usage can can go over 12 GB. Observed on MRE v2.0.0, with current Comfy. Needs investigating.

**Comment by MoonRide303** [comment]
It is somehow related to the changes introduced in vanilla betwen v1.0.67 and v2.0.0. MRE v1.0.67 (using same Comfy version) works fine (stays under 8 GB with Bloodstained).

**Comment by MoonRide303** [comment]
Same problem observed in the vanilla v2.0.0, and vanilla v1.0.67 worked fine - so it seems caused by recent @lllyasviel changes - I reported it as [vanilla issue #356](https://github.com/lllyasviel/Fooocus/issues/356).

**Comment by joanorsky** [comment]
Yes... there is something wierd with the LoRAs i can also confirm that. It consumes much more VRAM than before... making the lower VRAM systems to crash.

**Comment by MoonRide303** [comment]
Fixed in v2.0.3 (both vanilla, and MRE).
