### ISSUE TITLE
Feature request: login&pass for --share

### ISSUE THREAD

**Issue by Ravius** [MoonRide303/Fooocus-MRE#85]
Hi, can you add passing credentials with --share? cause sharing without it is insecure. 
would be smth like that. 
shared.gradio_root.launch(inbrowser=True, server_name=args.listen, server_port=args.port, share=args.share,
                          auth=('user','passw'))

**Comment by MoonRide303** [comment]
Done - you can define users in `auth.json` (use `auth-example.json` as a template). Passwords can go either as plaintext ("pass"), or sha256 hexdigests ("hash").
