### ISSUE TITLE
How can this problem be solved

### ISSUE THREAD

**Issue by bigmouth-GD** [MoonRide303/Fooocus-MRE#90]
Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
Fooocus version: 2.0.3 MRE
Inference Engine exists.
Git clone failed for Inference Engine: failed to send request: 操作超时

Total VRAM 8192 MB, total RAM 32632 MB
xformers version: 0.0.21
bin D:\Fooocus MRE\Fooocus-MRE-env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 2060 SUPER : native
VAE dtype: torch.float32
Using xformers cross attention
Running on local URL:  http://127.0.0.1:7860
model_type EPS
adm 2816
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: sd_xl_base_1.0_0.9vae.safetensors
Fooocus Expansion engine loaded.
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
Traceback (most recent call last):
  File "D:\Fooocus MRE\Fooocus-MRE\launch.py", line 137, in <module>
    from webui import *
  File "D:\Fooocus MRE\Fooocus-MRE\webui.py", line 488, in <module>
    shared.gradio_root.launch(inbrowser=True, server_name=args.listen, server_port=args.port, share=args.share)
  File "D:\Fooocus MRE\Fooocus-MRE-env\lib\site-packages\gradio\blocks.py", line 1971, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

**Comment by lanyusan** [comment]
`Git clone failed for Inference Engine: failed to send request: 操作超时`

Check your internet connection.

**Comment by bigmouth-GD** [comment]
谢谢，我已经解决了，应该是代理连接的问题
