### ISSUE TITLE
Feature Request: Run with All Styles

### ISSUE THREAD

**Issue by ptits** [MoonRide303/Fooocus-MRE#96]
I understand that implementing Plot X/Y/Z is  heavy load, so I am suggesting only ONE checkBox: "Run With All Styles".
It will run current prompt with All the styles and make 100+ images (logged already with log.html)
As long as Styles are secret weapon of Focus - nice galleries can be good promotion of Focus

It might also be "Run with Selected Styles" (but I usually run for all styles and then sort pictures of favour)

I added 4 lines of code to async_worker.py and use it for that:
        #from modules.sdxl_styles import style_keys
        #for key in style_keys:
            #style = key
            #pipeline.clean_prompt_cond_caches() 

Will be nice to have one checkBox to make batches for Styles

**Comment by barepixels** [comment]
Would be nice if the model and style name include in the file name.

**Comment by barepixels** [comment]
@ptits I have great news.  @runew0lf over at [RuinedFooocus](https://github.com/runew0lf/RuinedFooocus) have came up with a solution.  Using the multiple prompt feature in [RuinedFooocus](https://github.com/runew0lf/RuinedFooocus) one can batch render an image for each style.  

Read more about this here:  https://github.com/runew0lf/RuinedFooocus/issues/20

**Comment by MoonRide303** [comment]
Added in v2.0.78.5, as Style Iterator (commit [7e1728e](https://github.com/MoonRide303/Fooocus-MRE/commit/7e1728ee9507c7b8f68d57cb04164ccf246dd865)).

Can be used to check single styles (if no style is selected), or combinations with other styles (if 1 or more styles are selected).
